### ISSUE TITLE
Andor requires dlls

### ISSUE THREAD

**Issue by mfe5003** [QuantumQuadrate/CsPyController#1]
Not having the andor dlls installed will cause the controller to fail even if andor is not enabled.
Temp fix: comment out the andor instrument & analyses or install dlls

**Comment by kwnminho** [comment]
Need to correct the location of the file. Instead of

```
self.dll = CDLL(r"D:\git\cspycontroller\python\Andor\atmcd64d.dll")
```

Try something like

```
self.dll=CDLL("C:\\Users\\Rb\\LabSoftware\\CsPyNewGit\\CsPyController\\python\\Andor\\atmcd64d.dll")
```

**Comment by db314159** [comment]
I thought I had fixed that. Is that not on the github version? This is the DLL code I have:
try:
    self.dll = CDLL(r"D:\git\cspycontroller\python\Andor\atmcd64d.dll")
except Exception as e:
    logger.warning('Failed to load DLL for Andor (check path?): {}. Andor disabled.'.format(e))
    self.enable = False
    return

**Comment by mfe5003** [comment]
You're right.  I must have either been running an older version or I misunderstood what was breaking.
