### ISSUE TITLE
cycle time slows down if 'cycle experiment when not taking data' is checked

### ISSUE THREAD

**Issue by kwnminho** [QuantumQuadrate/CsPyController#10]
In certain timing and circumstances , CsPy seems to fill the deadtime between each measurements by inserting a fake cycle. Sometimes it leads to less data-taking rate.

**Comment by mfe5003** [comment]
The deadtime issue should be minimized by the threaded analysis that was just merged into the master branch with commit fa72e04.
Threading is not optimal, so we still need a multithreading implementation, see issue #11.
