### ISSUE TITLE
hdf5 issue

### ISSUE THREAD

**Issue by kwnminho** [QuantumQuadrate/CsPyController#3]
logger saying

Could not save variable experiment as an hdf5 dataset with value: <aqua.AQuA object at 0x0...something>
Object dtype dtype<'O'> has no native HDF5 equivalent

**Comment by mfe5003** [comment]
You need to add 'experiment' to the list of variables that are not recorded in the constants palette at the top.
We could probably add experiment to a default ignore list to make the warning go away.

**Comment by kwnminho** [comment]
ty
