### ISSUE TITLE
PIcam initialize library fails if no dll

### ISSUE THREAD

**Issue by mfe5003** [QuantumQuadrate/CsPyController#4]
If the princeton instruments dll is not on the system then, `picam` in [PiFunctions.py](https://github.com/QuantumQuadrate/CsPyController/blob/master/python/PythonForPicam/PiFunctions.py) is not defined and the PICams class initialization will fail.

@db314159

**Comment by mfe5003** [comment]
@db314159 please check my fix

**Comment by db314159** [comment]
I don't have a setup to test it on right now that doesn't have the dll 
installed, but it looks like it should work.

**Comment by mfe5003** [comment]
I tested it on my setup which doesn't can you test it on the one that does when you have a chance?

**Comment by db314159** [comment]
It works on the test installation I have on my laptop.
